### ISSUE TITLE
Bot gives this error

### ISSUE THREAD

**Issue by mattmad16** [GGrandma/SteamCardBot-v3#3]
/root/index.js:38
        console.log("[  DEBUG  ] Card data loaded. [" + Object.keys(DATA).length + "]");
                                                               ^

TypeError: Cannot convert undefined or null to object
    at Utils.getCardsInSets (/root/index.js:38:64)
    at Request.request [as _callback] (/root/utils.js:41:13)
    at Request.self.callback (/root/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)

**Comment by GGrandma** [comment]
Save your config and redownload the bot, this error is because the site the set data was hosted on went down.

**Comment by mattmad16** [comment]
thanks <3
